# Generated by Django 3.0.4 on 2020-04-14 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200413_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 10, 27, 48, 713642, tzinfo=utc)),
        ),
    ]
